INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (10,22,'start','C:\APPDATA\stats92.doc',6,9,5.11,78.92);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (15,98,'start','C:\APPDATA\DOC\agreement45.txt',2,16,93.97,8.62);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (16,96,'standard',NULL,8,25,52.03,61.43);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (20,85,'speciale','C:\TEMP\DOCS\contact11.html',11,29,39.4,70.98);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (26,48,'speciale',NULL,NULL,29,1.2,9.96);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (36,48,'speciale','C:\TEMP\contract62.docx',12,37,1.03,1.8);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (45,14,'start','C:\TEMP\DOC\ref61.xls',NULL,37,93.49,6.68);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (51,69,'standard','C:\TEMPORARY\DOC\contact99.doc',10,37,45.29,9.78);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (57,23,'start',NULL,20,NULL,86.61,76.4);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (61,87,'standard','C:\DATA\agreement55.docx',11,37,2.91,5.23);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (65,56,'standard','C:\DOCUMENTS\DOC\contact94.txt',1,40,73.76,3.49);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (67,46,'start','C:\DOCS\TEMP\contract55.doc',NULL,40,5.77,20.7);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (75,85,'speciale','C:\DOCS\work15.xml',2,40,14.04,8.93);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (80,38,'arrivo','C:\TEMPORARY\TEMP\refer43.txt',NULL,44,34.35,5.46);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (81,49,'standard','C:\DATA\refer98.docx',12,29,5.82,45.9);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (88,14,'start','C:\TEMP\DATA\sales26.xml',20,29,5.26,2.39);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (97,83,'standard',NULL,5,29,6.13,78.63);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (100,100,'arrivo',NULL,NULL,39,20.72,14.56);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (110,80,'standard','C:\TEMP\DOCS\contact99.txt',13,40,32.47,16.62);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (113,25,'arrivo','C:\TEMPORARY\RELS\ref88.xml',15,40,2.44,95.43);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (121,87,'standard','C:\APPDATA\contract56.xls',7,49,2.25,59.81);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (129,82,'arrivo','C:\DATA\DATA\contract28.xls',NULL,31,4.07,3.52);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (133,99,'standard','C:\TEMPORARY\RELS\contact69.xml',9,31,9.57,85.86);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (134,48,'speciale',NULL,NULL,31,5.72,4.82);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (138,26,'arrivo',NULL,7,NULL,68.51,3.11);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (143,80,'arrivo','C:\PROGRAM FILES\RELS\sales53.docx',2,31,42.06,1.62);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (150,43,'speciale','C:\DATA\DOCS\work98.doc',NULL,33,4.88,57.08);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (152,58,'arrivo','C:\APPDATA\TEMP\agreement37.doc',15,33,8.96,73.45);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (157,55,'standard',NULL,NULL,33,15.64,50.03);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (167,88,'speciale','C:\TEMPORARY\RELS\sales90.xml',9,40,28.44,18.96);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (171,30,'standard','C:\DOCS\RELS\personal48.xml',3,40,5.97,3.05);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (181,15,'standard','C:\TEMP\DATA\ref01.docx',20,40,18.91,31.9);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (191,83,'standard','C:\DATA\TEMP\refer85.html',3,50,5.81,64.61);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (200,63,'standard',NULL,NULL,50,47.33,12.9);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (210,10,'standard','C:\DOCUMENTS\TEMP\sales75.doc',NULL,50,9.42,3.11);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (213,91,'start','C:\DOCS\DOCS\work66.doc',17,31,7.78,59.37);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (223,84,'start',NULL,NULL,31,23.28,1.93);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (232,55,'standard','C:\DOCS\DATA\refer91.doc',4,40,6.08,6.08);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (241,70,'start','C:\TEMP\TEMP\refer84.html',6,48,53.43,57.66);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (243,72,'arrivo','C:\DOCUMENTS\DOCS\work19.xml',8,48,1.66,97.22);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (249,44,'start','C:\DATA\contract55.html',3,48,7.22,43.44);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (252,47,'start','C:\TEMP\TEMP\sales72.xls',7,49,7.14,9.01);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (254,71,'start','C:\TEMPORARY\TEMP\ref94.html',3,49,1.01,33.71);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (256,77,'start','C:\APPDATA\TEMP\sales09.xls',10,50,5.71,41.76);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (258,11,'start','C:\DOCS\DOC\personal14.docx',NULL,50,91.93,16.38);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (264,25,'start','C:\APPDATA\contract08.doc',18,50,64.93,1.32);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (271,7,'standard','C:\TEMP\TEMP\work54.doc',1,27,2.55,62.31);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (278,26,'start','C:\TEMPORARY\DATA\work96.docx',12,NULL,8.13,3.12);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (283,47,'speciale','C:\DATA\TEMP\personal54.docx',14,31,7.58,8.19);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (284,2,'arrivo','C:\DOCS\DOC\contract13.xls',4,41,6.86,8.21);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (291,35,'start','C:\PROGRAM FILES\DOCS\ref12.docx',NULL,41,93.76,68.45);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (297,29,'arrivo','C:\TEMP\RELS\personal71.html',13,26,86.98,19.66);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (305,62,'speciale','C:\DOCUMENTS\RELS\contact15.txt',NULL,26,5.58,3.38);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (312,24,'arrivo','C:\PROGRAM FILES\RELS\contract18.txt',6,30,88.32,16.06);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (314,47,'arrivo',NULL,NULL,32,60.59,5.8);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (320,88,'start','C:\DOCS\contact43.txt',8,41,71.44,7.87);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (330,63,'arrivo','C:\TEMPORARY\TEMP\refer74.txt',5,41,6.34,63.99);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (335,76,'speciale','C:\PROGRAM FILES\work23.xml',3,26,55.02,8.73);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (339,77,'standard','C:\TEMPORARY\DOC\refer20.docx',15,26,7.61,7.9);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (344,60,'speciale',NULL,NULL,26,83.88,1.2);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (348,78,'speciale','C:\TEMPORARY\contract46.html',3,34,2.98,9.65);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (352,14,'standard','C:\TEMP\TEMP\stats80.html',20,34,18.4,43.09);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (355,20,'start',NULL,1,43,9.53,48.74);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (360,4,'start','C:\TEMP\RELS\sales25.html',19,43,54.12,34.51);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (367,70,'standard','C:\TEMP\DOC\agreement43.txt',16,48,91.99,22.72);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (373,98,'arrivo','C:\TEMP\sales66.html',3,48,78.29,4.15);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (378,49,'speciale','C:\DATA\DATA\stats02.doc',NULL,48,74.31,8.98);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (380,8,'start',NULL,17,29,4.17,42.97);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (388,23,'speciale','C:\DOCUMENTS\RELS\ref84.docx',15,29,50.06,9.76);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (397,61,'start','C:\APPDATA\RELS\ref06.xls',7,37,42.07,1.42);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (407,79,'start','C:\DATA\DOC\stats00.txt',11,37,7.01,4.33);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (412,59,'standard',NULL,1,37,2.92,8.4);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (414,1,'start',NULL,4,47,98.58,82.56);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (423,55,'standard','C:\DOCUMENTS\DATA\personal91.html',NULL,47,56.88,7.49);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (426,27,'speciale','C:\TEMPORARY\DOC\contract70.html',12,47,22.52,5.1);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (433,77,'start','C:\DOCS\DOC\sales81.xls',6,26,8.62,74.69);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (435,49,'standard','C:\DOCS\TEMP\stats74.doc',13,26,84.77,3.56);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (440,14,'arrivo','C:\DOCUMENTS\TEMP\agreement13.html',10,26,49.91,3.21);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (450,39,'start',NULL,13,28,3.39,9.25);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (454,96,'speciale',NULL,14,35,4.4,50.26);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (455,9,'start',NULL,8,36,16.48,59.63);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (456,55,'start','C:\APPDATA\DOCS\agreement96.txt',20,36,5.55,36.92);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (460,45,'speciale','C:\APPDATA\refer34.docx',14,NULL,6.72,5.72);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (464,2,'speciale','C:\DATA\sales27.xls',NULL,37,3.79,93.05);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (470,76,'standard','C:\PROGRAM FILES\DATA\contract14.docx',3,37,9.54,6.15);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (472,26,'arrivo','C:\PROGRAM FILES\DOCS\refer65.xls',7,46,1.81,8.4);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (481,48,'start','C:\DOCUMENTS\DATA\stats19.xls',15,46,92.61,9.04);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (488,62,'standard','C:\PROGRAM FILES\refer51.doc',NULL,47,9.19,88.3);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (496,36,'standard',NULL,3,47,68.7,7.66);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (502,100,'start','C:\PROGRAM FILES\DATA\contact14.txt',14,47,3.84,34.35);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (505,38,'standard',NULL,8,32,60.74,9.38);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (506,14,'speciale','C:\TEMP\DATA\personal41.doc',13,32,1.34,46.33);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (507,2,'start','C:\TEMPORARY\DATA\personal36.xls',3,32,9.37,5.52);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (508,88,'arrivo','C:\DATA\DATA\agreement16.xml',8,42,66.77,4);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (518,77,'start','C:\TEMPORARY\TEMP\refer56.txt',NULL,27,4.91,55.09);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (528,10,'arrivo','C:\DOCUMENTS\DOC\contact05.doc',NULL,27,4.75,5.37);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (537,67,'start','C:\DATA\stats73.html',8,NULL,1.49,61.93);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (547,11,'standard','C:\DOCS\RELS\stats53.txt',14,29,1.69,56.31);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (551,22,'speciale','C:\APPDATA\DOC\contact87.html',NULL,29,4.44,2.48);
INSERT INTO "oca"."casella" ("idgioco","numeroordine","tipologia","video","destinazione","task","x","y") VALUES (558,97,'start',NULL,13,29,9.99,3.59);



