set search_path to "oca";

-- INSERIMENTO VALORI TABELLA ICONA
-- Numero tuple: 100
-- Spazio occupato su disco: 
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Beagle','Objects','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sweater','Planets','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Recycling truck','Plants','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sunglasses','Dresses','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sun','Planets','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Cat','Animals','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Octagon','Shoes','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Lime','Plants','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Fern','Plants','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Ellipse','Animals','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Hexagon','Objects','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Scarf','Dresses','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Police car','Animals','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Shoes','Animals','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Violet','Plants','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('T-shirt','Animals','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Helicopter','Vehicles','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Mercury','Plants','256x256','Carrot orange');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Flip-flops','Vehicles','256x256','Carrot orange');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Heptagon','Planets','256x256','Carrot orange');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Shirt','Planets','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sweatshirt','Dresses','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Balloon','Plants','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Mountain bike','Dresses','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Forklift','Shoes','256x256','Maya blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Moon','Planets','256x256','Maya blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Taxi','Objects','256x256','Alice blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Rectangle','Shapes','256x256','Alice blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Parallelogram','Planets','256x256','Alice blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Bicycle','Shapes','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Bear','Dresses','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Wildflower','Vehicles','256x256','Saffron');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Giraffe','Animals','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sneakers','Shoes','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Fire engine','Planets','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Thistle','Dresses','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('High heels','Shoes','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Airplane','Planets','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Scalene triangle','Plants','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Hat','Vehicles','256x256','Cerulean');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Saturn','Planets','256x256','Buff');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Tractor','Vehicles','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Tiger','Shoes','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Cube','Dresses','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Coat','Shoes','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Leopard','Animals','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Dress','Plants','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Fox','Animals','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Swimsuit','Shapes','256x256','White');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Trapezoid','Planets','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Circle','Shapes','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Scooter','Dresses','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Bonnet','Dresses','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Long coat','Objects','256x256','Hot Magenta');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Skateboard','Plants','256x256','Burnt umber');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Cylinder','Dresses','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Ant','Vehicles','256x256','Spring bud');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Elephant','Animals','256x256','Spring bud');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Decagon','Dresses','256x256','Burnt sienna');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Baboon ','Dresses','256x256','Burnt sienna');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Van','Plants','256x256','Burnt sienna');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Cap','Dresses','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Semi-circle','Shoes','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Shrub','Objects','256x256','Buff');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Racing car','Vehicles','256x256','Buff');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Heels','Shoes','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Jet','Objects','256x256','Cinnamon');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Jupiter','Planets','256x256','Hot Magenta');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Venus','Plants','256x256','Hot Magenta');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Turtle','Animals','256x256','Hot Magenta');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Oak','Plants','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Shorts','Shapes','256x256','Electric lime');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Space shuttle','Vehicles','256x256','Dark slate gray');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Hedge','Plants','256x256','Spring bud');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Crane','Shoes','256x256','Spring bud');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Cattail','Planets','256x256','Spring bud');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Hydrangea','Plants','256x256','Dark khaki');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Gloves','Dresses','256x256','Dark khaki');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Minus','Plants','256x256','Alice blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Mars','Animals','256x256','Burnt umber');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Caterpillar','Dresses','256x256','Burnt umber');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Bird','Shoes','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Square','Shapes','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Hoodies','Planets','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Sealion','Animals','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Suit','Objects','256x256','Dark chestnut');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Pointe shoes','Shoes','256x256','Burnt umber');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Skirt','Dresses','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Eagle','Animals','256x256','Electric purple');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Reed','Objects','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Boots','Animals','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Boat','Vehicles','256x256','Lavender');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Flippers','Shoes','256x256','Carrot orange');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Triangle','Dresses','256x256','Carrot orange');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Boar','Animals','256x256','Burnt sienna');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Motorcycle','Objects','256x256','Burnt sienna');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Dump truck','Planets','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Butterfly','Objects','256x256','Azure');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Ambulance','Animals','256x256','Alice blue');
INSERT INTO "oca"."icona" ("nome","tema","dimensione","set") VALUES ('Deer','Animals','256x256','Alice blue');