-- INSERIMENTO TUPLE TABELLA ANAGRAFICAUTENTE
-- Numero tuple: 100
-- Spazio occupato su disco: 

INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Will.Pyland@lycos.be','Ellie25','Simon','Polti','16/08/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Hans.Aldritch@telefonica.co.uk','Joey6',NULL,'Green','10/08/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('HansChwatal@gmail.it','Benjamin32','Truus',NULL,'12/02/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Norbert.Barnett@telfort.be','Andrea5','Bess',NULL,'25/11/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Fred.Rivers1@dolfijn.it','Sharon','Harry','Hoyt','30/10/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Lynn.Muench@mymail.cn','Bertje','Jolanda','Ostanik','17/04/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('GFramus2@yahoo.ca','Nicolas695','Ricardo','Byrnes',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('G.Tudisco@kpn.net','Zofia6',NULL,'Barbee','09/04/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('HansBuchholz3@web.gov','Sharon06','Lucia','Anderson',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('William.Love2@live.us','Daniela',NULL,'van het Hof','06/02/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('RickOrcutt@telfort.net','Jan','Jeffery','Kellock','11/08/1988');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Maddyvan der Laar2@kpn.es','GoSix17','Jim',NULL,'15/10/1992');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Gretsj.Gua Lima@lycos.fr','Bob',NULL,'Deans','12/05/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Hank.Zia3@lycos.dk','Carlos38','Kimberly','Brady',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('JeanRobbins@kpn.nl','Barbara588',NULL,'Chwatal',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('TNaff@mymail.fr','Rolla','Alba','Knopp',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Bianca.Depew@aol.es','Matthew581','Pieter','Crocetti',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('C.Baltec@gmail.ca','Sean19','Emma','Hancock','03/08/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Bas.Kepler4@web.gov','Tony538','Tim','Muench','03/07/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BasForsberg@mymail.net','Sogood4','Rik',NULL,'15/07/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Paul.Gunter@lycos.us','Charles','Camilla','Mitchell','18/06/1988');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('IWarner@libero.ca','Dorothy481','Rachael',NULL,'28/09/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('TreesCramer5@yahoo.de','Talitha','Ricardo','Duvall','24/12/1992');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BrentScheffold3@myspace.dk','Nico0','Nico',NULL,'01/08/1988');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('SuzanneFriedman@msn.gov','Madison','Jacob','Anderson',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('TonGreen3@gawab.org','Matthew098','Femke','Weaver','01/07/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Liam.Korkovski4@live.cn','Stanislaw70','Roger',NULL,NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Hans.Manson3@excite.fr','Gillian490','Robert','Nelson','03/11/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Lucy.Korkovski@msn.es','Edwina4','Paula','Queen','18/03/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MPhelps@excite.no','Jessica','Amy',NULL,'20/10/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Frank.Herzog@telefonica.ca','Charlie','Mads',NULL,'05/05/1998');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MilanGua Lima@gawab.us','Suzanne74',NULL,'Mitchell','20/10/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('FrankPetrzelka@msn.no','Jolanda','Mathilde','Brumley','24/07/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Frank.Dean@gawab.nl','Scotty5',NULL,'van der Laar','06/09/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('RonGerschkow@telfort.us','Peg56','Stephen','Goodman','20/04/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('YAntonucci@excite.org','Lu4',NULL,NULL,'09/11/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Johan.Zia@excite.de','Christa',NULL,'van Dijk','12/02/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('NickCramer@lycos.net','Pawel33','Katie',NULL,'05/03/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BillKoch@hotmail.gov','Jaclyn','Adam','Brown','01/07/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MattijsMuench2@excite.com','Ollie','Sophia','Guyer','07/01/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('EricFramus3@excite.it','Michel',NULL,'Forsberg','01/02/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MartinRichter@myspace.us','Rich','Diego','Wesolowski','02/08/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Bianca.Nahay@hotmail.gov','Adrian136','Daan','Seibel','09/06/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('GMoore1@mymail.dk','Margo60','Scotty','Sterrett',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Fred.Dean@hotmail.de','Victor19','Laura','Weaver','31/08/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BrentHelfrich@gawab.it','Lucille1',NULL,NULL,'03/03/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('FransAyers2@live.de','Amber71',NULL,NULL,'22/08/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('FrankNahay@excite.co.uk','Daniela844','Nicolas','Morton','19/05/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('DCohen@hotmail.no','Dave','Sara','Brady','05/05/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Frans.Deleo4@libero.org','Nicoline94','Kay','Wilson','19/12/1992');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('WilliamWhite2@aol.org','Jacob6','David','Bugno','15/06/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Pauline.Walker@aol.es','Mick','Ted','Cragin','25/11/1992');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MBrown4@libero.gov','Gabrielle012','Joanne',NULL,'21/05/1998');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Frank.Press@weboffice.no','Jesse','Babet','Kepler','01/05/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Otto.Julieze@telefonica.co.uk','David63','Mick','Warner',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('LiamMaribarski@aol.de','Thomas','Michel',NULL,'28/08/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BasAyers1@gmail.us','Francisco975',NULL,NULL,'23/06/1993');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Fred.Deans@weboffice.it','Adrian','Giel','Haynes','18/07/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('LeonBeckbau2@telefonica.cc','Sandra57',NULL,'Cain',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('RichardChapman4@freeweb.es','Chloe3','Teddy','Martin','04/07/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Y.Anderson@telefonica.cn','Joe457','Malgorzata',NULL,'22/11/1998');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MartinStorrs@myspace.fr','Michel234','Conor','Hancock','17/04/1996');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('V.Cantere4@web.co.uk','Isaac81','Sjon','Stewart','18/11/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('R.Hankins2@gawab.fr','Samantha','Jessica','Waldo','01/10/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('B.Polti5@kpn.no','Freja95',NULL,'Pekaban',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('JeanDavis3@myspace.net','Jamie585',NULL,'Mitchell','09/08/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BrentOverton3@freeweb.us','Liza6',NULL,NULL,'03/12/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Hans.King@weboffice.fr','Vanessa904','Joshua','Wood','10/10/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Richard.Stevens1@mail.us','Alexis43','Taylor','Haynes','11/11/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Victor.Whitehurst@live.it','Katharina536','Mary','Thompson','02/01/1999');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BrentPickering@web.be','JanCees415','Willy','Anthony','08/06/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('ILiddle4@telfort.be','William362','Pete','Lamere','07/12/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('SuusGunter@freeweb.cc','Charles','Jaap','Helfrich',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Leon.Beckbau@mobileme.co.uk','Gabbie7','Sem','Dean','11/02/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('WilliamDavis@telfort.cn','Sjef','Esther',NULL,'12/09/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('MKuehn@telefonica.gov','Marie4','Nienke','Willis','08/10/1994');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Geoffry.Millis@weboffice.us','Giood2',NULL,NULL,'04/02/1998');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Hank.Robinson@msn.be','Susan','Chris','Kuehn','11/10/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Frank.Shapiro@mymail.com','Ben7','Kay',NULL,NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Bas.Mitchell1@freeweb.it','Peter1','Adam',NULL,'06/03/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('GJackson4@hotmail.it','Jessica05','Jan',NULL,'11/11/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Basvan Dijk@libero.de','Anthony9','Callum','Slocum',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BartFrancis5@myspace.ca','Sophie2','Malgorzata','Paddock',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('P.Carlos@telfort.be','Kimmy','Ryan','Wakefield','11/04/1990');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('P.Little@yahoo.nl','Marco720','Ollie','Symms','01/02/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('DWalker3@yahoo.fr','Helen1','Maaike','Cooper','07/08/1987');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Emma.Noteboom@mail.nl','Camille375','Rogier',NULL,NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('U.Caffray@weboffice.net','Erin84','Michael','Trainor','09/06/1997');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('K.Mitchell2@yahoo.cc','Liam38',NULL,'Cappello','11/07/1988');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('VictorTrainor@telefonica.com','Saskia','Julia','Alspaugh','07/06/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Trees.Ayers@aol.fr','Rogier938',NULL,'Williamson','09/01/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('KCaouette@live.com','Charles','Helma','Ionescu',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('E.Arcadi4@lycos.be','Bill489','Sjef',NULL,'09/03/1998');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('C.Koss@gawab.com','Simon19','Duncan','Schmidt',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('BillStevens3@excite.nl','Joe9',NULL,'Jackson','07/07/1991');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('HansMayberry1@msn.us','Lizzy777','Bengie','Wood',NULL);
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('VictoriaNithman@dolfijn.be','Daniel','Samuel',NULL,'05/02/1989');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Royvan der Laar4@yahoo.dk','Ulla',NULL,'Frega','02/02/1995');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('Bianca.Morton@gmail.cn','Luca65','Scott',NULL,'04/06/1988');
INSERT INTO "oca"."anagraficautente" ("email","nickname","nome","cognome","datan") VALUES ('PeterWilliamson5@mail.de','Roger',NULL,'Slater',NULL);